function [text,tex,conditions] = renderResult(r)
%RENDERRESULT Chinese derivation with explicit state and channel ordering.
s=char(r.laplaceVariable); sl=latex(r.laplaceVariable);
lines={'适用条件：连续时间线性时不变模型；所列参数在一次分析中保持常数。', ...
    '所有保留参数默认为实数，不默认其为正数；须同时满足以下原式定义域条件。', ...
    '传递函数采用零初值 x(0)=0；模型中指定的非零初始状态响应不包含在传递函数内。'};
if isempty(r.domainConditions)
    lines{end+1}='原式没有额外的除法或实数幂定义域约束。';
else
    for k=1:numel(r.domainConditions)
        d=r.domainConditions(k);
        lines{end+1}=sprintf('原式定义域 [%s，%s] %s：%s。', ...
            d.label,d.kind,d.source,char(d.relation)); %#ok<AGROW>
    end
end
lines{end+1}=sprintf('状态消元要求 det(%s I-A) ~= 0，即 %s；即使通道约简消去极点，原状态消元条件仍保留。', ...
    s,char(r.resolventCondition));
lines{end+1}='上述条件的交集为有效域；未将参数限制为正数，也未枚举非线性模型偶然退化为线性的特殊参数值。';
conditions=strjoin(lines,newline);
body={conditions,'', ...
    ['状态顺序 x = [' strjoin(r.stateNames,', ') ']^T'], ...
    ['输入顺序 u = [' strjoin(r.inputNames,', ') ']^T'], ...
    ['输出顺序 y = [' strjoin(r.outputNames,', ') ']^T'], ...
    ['保留为实符号的参数：' strjoin(r.symbolicParameters,', ')], ...
    '状态空间：dx/dt = A*x + B*u；y = C*x + D*u', ...
    ['A = ' char(r.A)], ['B = ' char(r.B)], ...
    ['C = ' char(r.C)], ['D = ' char(r.D)], '', ...
    '推导依据：对安全 AST 逐节点构造符号式；符号 Jacobian 不含状态或输入，且原式减去 Jacobian*z 恒等于零。', ...
    sprintf('零初值拉普拉斯变换：(%s I-A)X=B U，Y=C X+D U。',s), ...
    sprintf('因此 G(%s)=C(%s I-A)^(-1)B+D。',s,s), ...
    ['传递矩阵 G = ' char(r.transferMatrix)]};
texRows={['\dot{x}=Ax+Bu,\quad y=Cx+Du,\quad x(0)=0'], ...
    ['A=' latex(r.A) ',\quad B=' latex(r.B)], ...
    ['C=' latex(r.C) ',\quad D=' latex(r.D)], ...
    ['G(' sl ')=C(' sl 'I-A)^{-1}B+D=' latex(r.transferMatrix)]};
for iy=1:numel(r.outputNames)
    for iu=1:numel(r.inputNames)
        body{end+1}=sprintf('通道 %s <- %s：G(%s) = %s', ...
            r.outputNames{iy},r.inputNames{iu},s,char(r.transferMatrix(iy,iu))); %#ok<AGROW>
        texRows{end+1}=['G_{' identifier(r.outputNames{iy}) '\leftarrow ' ...
            identifier(r.inputNames{iu}) '}(' sl ')=' latex(r.transferMatrix(iy,iu))]; %#ok<AGROW>
    end
end
for k=1:numel(r.domainConditions)
    texRows{end+1}=['\text{原式定义域：}\quad ' latex(r.domainConditions(k).relation)]; %#ok<AGROW>
end
texRows{end+1}=['\det(' sl ' I-A)\ne 0:\quad ' latex(r.resolventCondition)];
texRows{end+1}='\text{参数为实常数；零初值；以上条件同时成立。}';
text=strjoin(body,newline);
% strjoin interprets delimiter escapes even when supplied as a char vector.
% Concatenate literal line separators so LaTeX receives exactly two slashes.
texBody=texRows{1};
for k=2:numel(texRows)
    texBody=[texBody ' \\' newline texRows{k}]; %#ok<AGROW>
end
tex=sprintf('\\begin{gathered}\n%s\n\\end{gathered}',texBody);
end
function text=identifier(name)
text=['\mathrm{' strrep(name,'_','\_') '}'];
end
